const provinceList = [
  { name: "Salta", cp: "A" },
  { name: "Buenos Aires", cp: "B" },
  { name: "Chaco", cp: "H" },
  { name: "Chubut", cp: "U" },
  { name: "Ciudad Autónoma de Buenos Aires", cp: "C" }, 
  { name: "Catamarca", cp: "K" },
  { name: "Córdoba", cp: "X" },
  { name: "Corrientes", cp: "W" },
  { name: "Entre Ríos", cp: "E" },
  { name: "Formosa", cp: "P" },
  { name: "Jujuy", cp: "Y" },
  { name: "La Pampa", cp: "L" },
  { name: "La Rioja", cp: "F" },
  { name: "Mendoza", cp: "M" },
  { name: "Misiones", cp: "N" },
  { name: "Neuquén", cp: "Q" },
  { name: "Río Negro", cp: "R" },
  { name: "San Juan", cp: "J" },
  { name: "San Luis", cp: "D" },
  { name: "Santa Cruz", cp: "Z" },
  { name: "Santa Fe", cp: "S" },
  { name: "Santiago del Estero", cp: "G" },
  { name: "Tierra del Fuego", cp: "V" },
  { name: "Tucumán", cp: "T" },
];

export default provinceList;
